chore: test precommit

diff --git a/.scripts/git-hooks/pre-commit b/.scripts/git-hooks/pre-commit
--- a/.scripts/git-hooks/pre-commit
+++ b/.scripts/git-hooks/pre-commit
@@ -68,4 +68,17 @@ then
     fi
 fi
 
+if [ "$FILES" != "" ]
+then
+    echo "Running PHPCS Check..."
+    composer phpcs -n $FILES
+    if [ $? != 0 ]
+    then
+        echo "Please fix the PHPCS errors before commit!"
+        echo " => Run this command to check PHPCS errors."
+        echo "		composer lint:stan"
+        exit 1
+    fi
+fi
+
 exit $?
